---

api_key: fakekey
galaxy_instance: http://127.0.0.1:4001
install_repository_dependencies: true
install_resolver_dependencies: true
install_tool_dependencies: false

tools:
  - name: suite_pdaug
    owner: jay
    tool_panel_section_label: "PDAUG Galaxy"